server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://47.116.216.13/study?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kami7777777!
logging:
  level:
    com.example.demo: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  type-aliases-package: com.example.demo.po
  global-config:
    db-config:
      id-type: auto
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - priv.kami.study.controller
